<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Mohits-MacBook-Air.local" ignored="6" name="Default test" tests="1" failures="0" timestamp="10 Jun 2018 06:24:34 GMT" time="2.58" errors="0">
  <testcase name="statusCode_401_UNAUTHORIZED_multiply_path" time="2.526" classname="com.qa.tests.ErrorCodesTest"/>
  <testcase name="statusCode_404_NOT_FOUND" time="0.0" classname="com.qa.tests.ErrorCodesTest">
    <ignored/>
  </testcase> <!-- statusCode_404_NOT_FOUND -->
  <testcase name="additionTest_400_Bad_Request" time="0.0" classname="com.qa.tests.ErrorCodesTest">
    <ignored/>
  </testcase> <!-- additionTest_400_Bad_Request -->
  <testcase name="statusCode_401_UNAUTHORIZED_division_path" time="0.0" classname="com.qa.tests.ErrorCodesTest">
    <ignored/>
  </testcase> <!-- statusCode_401_UNAUTHORIZED_division_path -->
  <testcase name="statusCode_401_UNAUTHORIZED_addition_path" time="0.0" classname="com.qa.tests.ErrorCodesTest">
    <ignored/>
  </testcase> <!-- statusCode_401_UNAUTHORIZED_addition_path -->
  <testcase name="divisionTest_400_Bad_Request" time="0.0" classname="com.qa.tests.ErrorCodesTest">
    <ignored/>
  </testcase> <!-- divisionTest_400_Bad_Request -->
  <testcase name="multiplytest_400_Bad_Request" time="0.0" classname="com.qa.tests.ErrorCodesTest">
    <ignored/>
  </testcase> <!-- multiplytest_400_Bad_Request -->
</testsuite> <!-- Default test -->
